# frozen_string_literal: true

namespace :appraisal do
  desc "Check appraisals"
  task :check do
    Appraisal::AppraisalFile.each do |appraisal|
      existing = File.read(appraisal.gemfile_path)
      signature = Appraisal::Customize.heading || "This file was generated by Appraisal"
      header = appraisal.send :comment_lines, signature
      body = appraisal.send :quoted_gemfile
      expected = [header, body].join("\n\n")
      raise "Outdated appraisal: #{appraisal.name}" unless existing.chomp == expected.chomp
    end
  end
end
