# frozen_string_literal: true

# HACK: This uses odd syntax to make appraisal customization work on newer Rubies.
# See https://github.com/thoughtbot/appraisal/pull/214. Once that one has been
# released, we should use customize_gemfiles instead.
Customize.new heading: <<~HEADING.chomp
  frozen_string_literal: true

  This file was generated by Appraisal
HEADING

appraise "rails_70" do
  gem "rails", "~> 7.0.0"
end

appraise "rails_71" do
  gem "rails", "~> 7.1.0"
end
